### ISSUE TITLE
What is this usage?

### ISSUE THREAD

**Issue by stevechesley** [Meet-Vyas-Dev/InterPython_Workshop_Example#1]
`f` seems to be doing something here but not sure what...

https://github.com/Meet-Vyas-Dev/InterPython_Workshop_Example/blob/a090d2e272e86dc38a615f68d789ce664c9819e4/tests/test_models.py#L86

**Comment by Meet-Vyas-Dev** [comment]
So, the f here represents an f-string introduced in Python 3.6. These f strings, also called formatted strings, are a way to write more concise and readable expressions inside string literals. Any valid python expression can be kept inside these {} brackets, making printing results with expressions much more accessible. If you have more questions, feel free to ask.

**Comment by stevechesley** [comment]
Newish to python. Did not know that...
