### ISSUE TITLE
Improve the structure of the notebook

### ISSUE THREAD

**Issue by ShrRa** [Meet-Vyas-Dev/InterPython_Workshop_Example#3]
Hello,
There are some improvements to the structure of the `light-curve-analysis.ipynb` notebook to be done:

1. There are some runaway imports.
2. The sectioning is unclear, visualization is apparently happening in the 'Read the data'
3. The code does not comply with the PEP 8.

**Comment by Meet-Vyas-Dev** [comment]
I have fixed the notebook to fit the standards, although it is not completely done and I am still editing the notebook.
